VAZ-Admin_New/sb-admin-2.Web/Models/Navbar.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace sb_admin_2.Web.Models
{
    public class Navbar
    {
        public int Id { get; set; }
        public string nameOption { get; set; }
        public string controller { get; set; }
        public string action { get; set; }
        public string area { get; set; }
        public string imageClass { get; set; }
        public string activeli { get; set; }
        public bool status { get; set; }
        public int parentId { get; set; }
        public bool isParent { get; set; }
    }
}

VAZ-Admin_New/sb-admin-2.Web/Controllers/NavbarController.cs
using sb_admin_2.Web.Domain;
using sb_admin_2.Web.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace sb_admin_2.Web.Controllers
{
    public class NavbarController : Controller
    {
        // GET: Navbar
        public ActionResult Index()
        {
            var data = new Data();            
            return PartialView("_Navbar", data.navbarItems().ToList());
        }
    }
}

VAZ-Admin_New/sb-admin-2.Web/Views/Shared/_Layout.cshtml
<!-- - var menuBorder = true-->
<!DOCTYPE html>
<html lang="en" data-textdirection="ltr" class="loading">
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=0, minimal-ui">
    <meta name="description" content="View Ads Zone.">
    <meta name="keywords" content="View Ads Zone">
    <meta name="author" content="View Ads Zone">
    <title>Andhra Views</title>
    <link rel="apple-touch-icon" href="~/web/app-assets/images/ico/apple-icon-120.png">
    <link rel="shortcut icon" type="image/x-icon" href="~/web/app-assets/images/ico/favicon.ico">
    <link href="https://fonts.googleapis.com/css?family=Montserrat:300,300i,400,400i,500,500i%7COpen+Sans:300,300i,400,400i,600,600i,700,700i" rel="stylesheet">
    <!-- BEGIN VENDOR CSS-->
    <link rel="stylesheet" type="text/css" href="~/web/app-assets/css/vendors.css">
    <link rel="stylesheet" type="text/css" href="~/web/app-assets/vendors/css/tables/datatable/datatables.min.css">
    <!-- END VENDOR CSS-->
    <!-- BEGIN STACK CSS-->
    <link rel="stylesheet" type="text/css" href="~/web/app-assets/css/app.min.css">
    <!-- END STACK CSS-->
    <!-- BEGIN Page Level CSS-->
    <link rel="stylesheet" type="text/css" href="~/web/app-assets/css/core/menu/menu-types/vertical-menu.min.css">
    <!-- END Page Level CSS-->
    <!-- BEGIN Custom CSS-->

    <link rel="stylesheet" type="text/css" href="~/web/app-assets/fonts/simple-line-icons/style.min.css">
    <link rel="stylesheet" type="text/css" href="~/web/app-assets/assets/css/style.css">
    <!-- END Custom CSS-->
    <!-- BEGIN VENDOR CSS-->
   
    <link rel="stylesheet" type="text/css" href="~/web/app-assets/vendors/css/pickers/daterange/daterangepicker.css">
    <link rel="stylesheet" type="text/css" href="~/web/app-assets/vendors/css/pickers/datetime/bootstrap-datetimepicker.css">
    <link rel="stylesheet" type="text/css" href="~/web/app-assets/vendors/css/pickers/pickadate/pickadate.css">
    <!-- END VENDOR CSS-->
    <!-- BEGIN STACK CSS-->
    <link rel="stylesheet" type="text/css" href="~/web/app-assets/css/app.min.css">
    <!-- END STACK CSS-->
    <!-- BEGIN Page Level CSS-->
    <link rel="stylesheet" type="text/css" href="~/web/app-assets/css/core/menu/menu-types/vertical-menu-modern.css">
    <link rel="stylesheet" type="text/css" href="~/web/app-assets/css/core/colors/palette-gradient.min.css">
    <link rel="stylesheet" type="text/css" href="~/web/app-assets/css/plugins/pickers/daterange/daterange.min.css">
    <!-- END Page Level CSS-->
    <!-- BEGIN Custom CSS-->
    <link rel="stylesheet" type="text/css" href="~/web/app-assets/assets/css/style.css">
    <!-- END Custom CSS-->
    <link href="https://fonts.googleapis.com/css?family=Montserrat:300,300i,400,400i,500,500i%7COpen+Sans:300,300i,400,400i,600,600i,700,700i"
          rel="stylesheet">

    <script src="~/bower_components/jquery/dist/jquery.min.js"></script>


    <style>
        a.btn.btn-primary.btn-secondary.buttons-copy.buttons-html5.mr-1{
            display:none;
        }
        a.btn.btn-primary.btn-secondary.buttons-csv.buttons-html5.mr-1 {
            display: none;
        }
        a.btn.btn-primary.btn-secondary.buttons-excel.buttons-html5.mr-1 {
            display: none;
        }
        a.btn.btn-primary.btn-secondary.buttons-pdf.buttons-html5.mr-1 {
            display: none;
        }
        a.btn.btn-primary.btn-secondary.buttons-print.btn-primary.mr-1 {
            display: none;
        }
    </style>
</head>
<body data-open="click" data-menu="vertical-menu" data-col="2-columns" class="vertical-layout vertical-menu 2-columns   menu-expanded fixed-navbar">
    @Html.Action("Index", "Navbar")


    
    <div class="app-content content"> 
            @RenderBody()



         
    </div>
    <footer class="footer footer-static footer-light navbar-border">
        <p class="clearfix blue-grey lighten-2 text-sm-center mb-0 px-2">
            <span class="float-md-left d-block d-md-inline-block">
                Copyright &copy; 2018 <a href="http://www.viewadszone.com/"
                                         target="_blank" class="text-bold-800 grey darken-2">www.andhraviews.com</a>, All rights
                reserved.
            </span>
            <span class="float-md-right d-block d-md-inline-blockd-none d-lg-block"></span>
        </p>
    </footer>
    <!-- BEGIN VENDOR JS-->
    <script src="~/web/app-assets/vendors/js/vendors.min.js" type="text/javascript"></script>
    <!-- BEGIN VENDOR JS-->
    <!-- BEGIN PAGE VENDOR JS-->
    <script src="~/web/app-assets/vendors/js/tables/datatable/datatables.min.js" type="text/javascript"></script>
    <script src="~/web/app-assets/vendors/js/tables/datatable/dataTables.buttons.min.js"
            type="text/javascript"></script>
    <script src="~/web/app-assets/vendors/js/tables/buttons.flash.min.js" type="text/javascript"></script>
    <script src="~/web/app-assets/vendors/js/tables/jszip.min.js" type="text/javascript"></script>
    <script src="~/web/app-assets/vendors/js/tables/pdfmake.min.js" type="text/javascript"></script>
    <script src="~/web/app-assets/vendors/js/tables/vfs_fonts.js" type="text/javascript"></script>
    <script src="~/web/app-assets/vendors/js/tables/buttons.html5.min.js" type="text/javascript"></script>
    <script src="~/web/app-assets/vendors/js/tables/buttons.print.min.js" type="text/javascript"></script>
    <!-- END PAGE VENDOR JS-->
    <!-- BEGIN STACK JS-->
    <script src="~/web/app-assets/js/core/app-menu.min.js" type="text/javascript"></script>
    <script src="~/web/app-assets/js/core/app.min.js" type="text/javascript"></script>
    <script src="~/web/app-assets/js/scripts/customizer.min.js" type="text/javascript"></script>
    <!-- END STACK JS-->
    <!-- BEGIN PAGE LEVEL JS-->
    <script src="~/web/app-assets/js/scripts/tables/datatables/datatable-advanced.js"
            type="text/javascript"></script>
    <!-- END PAGE LEVEL JS-->

    <!-- BEGIN PAGE VENDOR JS-->
    <script src="~/web/app-assets/vendors/js/pickers/dateTime/moment-with-locales.min.js" type="text/javascript"></script>
    <script src="~/web/app-assets/vendors/js/pickers/dateTime/bootstrap-datetimepicker.min.js" type="text/javascript"></script>
    <script src="~/web/app-assets/vendors/js/pickers/pickadate/picker.js" type="text/javascript"></script>
    <script src="~/web/app-assets/vendors/js/pickers/pickadate/picker.date.js" type="text/javascript"></script>
    <script src="~/web/app-assets/vendors/js/pickers/pickadate/picker.time.js" type="text/javascript"></script>
    <script src="~/web/app-assets/vendors/js/pickers/pickadate/legacy.js" type="text/javascript"></script>
    <script src="~/web/app-assets/vendors/js/pickers/daterange/daterangepicker.js" type="text/javascript"></script>
    <!-- END PAGE VENDOR JS-->
    <!-- BEGIN PAGE LEVEL JS-->
    <script src="~/web/app-assets/js/scripts/pickers/dateTime/picker-date-time.js" type="text/javascript"></script>

    <link rel="stylesheet" href="~/docs/css/bootstrap-example.min.css" type="text/css">
    <link rel="stylesheet" href="~/docs/css/prettify.min.css" type="text/css">

    <script type="text/javascript" src="~/docs/js/bootstrap-3.3.2.min.js"></script>
    <script type="text/javascript" src="~/docs/js/prettify.min.js"></script>
    <link rel="stylesheet" href="~/dist/css/bootstrap-multiselect.css" type="text/css">
    <script type="text/javascript" src="~/dist/js/bootstrap-multiselect.js"></script>


    @*<!-- BEGIN VENDOR JS-->
    <!-- BEGIN VENDOR JS-->
    <script src="~/web/app-assets/vendors/js/vendors.min.js" type="text/javascript"></script>
    <!-- BEGIN VENDOR JS-->
    <script src="~/web/app-assets/vendors/js/vendors.min.js" type="text/javascript"></script>
    <!-- BEGIN VENDOR JS-->
   
    <!-- BEGIN STACK JS-->
    <script src="~/web/app-assets/js/core/app-menu.min.js" type="text/javascript"></script>
    <script src="~/web/app-assets/js/core/app.min.js" type="text/javascript"></script>
    <script src="~/web/app-assets/js/scripts/customizer.min.js" type="text/javascript"></script>
    <!-- END STACK JS-->
    <!-- BEGIN PAGE LEVEL JS-->
    <script src="~/web/app-assets/js/scripts/tables/datatables/datatable-advanced.js" type="text/javascript"></script>
    <!-- END PAGE LEVEL JS-->
   
    <!-- BEGIN PAGE VENDOR JS-->
    <script src="~/web/app-assets/vendors/js/pickers/dateTime/moment-with-locales.min.js" type="text/javascript"></script>
    <script src="~/web/app-assets/vendors/js/pickers/dateTime/bootstrap-datetimepicker.min.js" type="text/javascript"></script>
    <script src="~/web/app-assets/vendors/js/pickers/pickadate/picker.js" type="text/javascript"></script>
    <script src="~/web/app-assets/vendors/js/pickers/pickadate/picker.date.js" type="text/javascript"></script>
    <script src="~/web/app-assets/vendors/js/pickers/pickadate/picker.time.js" type="text/javascript"></script>
    <script src="~/web/app-assets/vendors/js/pickers/pickadate/legacy.js" type="text/javascript"></script>
    <script src="~/web/app-assets/vendors/js/pickers/daterange/daterangepicker.js" type="text/javascript"></script>
    <!-- END PAGE VENDOR JS-->
    <!-- BEGIN PAGE LEVEL JS-->
    <script src="~/web/app-assets/js/scripts/pickers/dateTime/picker-date-time.js" type="text/javascript"></script>
    <!-- BEGIN PAGE VENDOR JS-->
    <script src="~/web/app-assets/vendors/js/tables/datatable/datatables.min.js" type="text/javascript"></script>
    <script src="~/web/app-assets/vendors/js/tables/datatable/dataTables.buttons.min.js" type="text/javascript"></script>
    <script src="~/web/app-assets/vendors/js/tables/buttons.flash.min.js" type="text/javascript"></script>
    <script src="~/web/app-assets/vendors/js/tables/jszip.min.js" type="text/javascript"></script>
    <script src="~/web/app-assets/vendors/js/tables/pdfmake.min.js" type="text/javascript"></script>
    <script src="~/web/app-assets/vendors/js/tables/vfs_fonts.js" type="text/javascript"></script>
    <script src="~/web/app-assets/vendors/js/tables/buttons.html5.min.js" type="text/javascript"></script>
    <script src="~/web/app-assets/vendors/js/tables/buttons.print.min.js" type="text/javascript"></script>
    <!-- END PAGE VENDOR JS-->*@
</body>
</html>

VAZ-Admin_New/sb-admin-2.Web/Views/Shared/_LoginLayout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">
    <title>Andhra Views</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    <!-- DataTables CSS -->
    <link href="@Url.Content("~/bower_components/datatables-plugins/integration/bootstrap/3/dataTables.bootstrap.css")" rel="stylesheet" type="text/css" />
    <!-- DataTables Responsive CSS -->
    <link href="@Url.Content("~/bower_components/datatables-responsive/css/dataTables.responsive.css")" rel="stylesheet" type="text/css" />
    <link href="@Url.Content("~/bower_components/morrisjs/morris.css")" rel="stylesheet" type="text/css" />
    <link href="@Url.Content("~/bower_components/font-awesome/css/font-awesome.min.css")" rel="stylesheet" type="text/css" />
    <!-- jQuery -->
    @Scripts.Render("~/bundles/jquery")
    <script src="@Url.Content("~/bower_components/jquery/dist/jquery.min.js")"></script>
    @Scripts.Render("~/bundles/bootstrap")
    <script src="@Url.Content("~/bower_components/metisMenu/dist/metisMenu.min.js")"></script>
</head>
<body>
    <div id="wrapper">
        <!-- Navigation -->
  

       
            @RenderBody()
       
        <!-- /#page-wrapper -->
    </div>
    <!-- /#wrapper -->
    <!-- DataTables JavaScript -->
    <script src="@Url.Content("~/bower_components/raphael/raphael-min.js")"></script>

    <!-- DataTables JavaScript -->
    <script src="@Url.Content("~/bower_components/datatables/media/js/jquery.dataTables.min.js")"></script>
    <script src="@Url.Content("~/bower_components/datatables-plugins/integration/bootstrap/3/dataTables.bootstrap.min.js")"></script>
    <!-- Custom Theme JavaScript -->
    <script src="@Url.Content("~/Scripts/sb-admin-2.js")"></script>
    <!-- Page-Level Demo Scripts - Tables - Use for reference -->
    <script>
        $(document).ready(function () {
            $('#dataTables-example').DataTable({
                responsive: true
            });
        });
    </script>
    @RenderSection("scripts", required: false)
</body>
</html>

VAZ-Admin_New/sb-admin-2.Web/Views/Shared/_Navbar.cshtml
@model IEnumerable<sb_admin_2.Web.Models.Navbar>

 <!-- fixed-top-->
<nav class="header-navbar navbar-expand-md navbar navbar-with-menu fixed-top navbar-light navbar-border">
    <div class="navbar-wrapper">
        <div class="navbar-header">
            <ul class="nav navbar-nav flex-row">
                <li class="nav-item mobile-menu d-md-none mr-auto"><a href="#" class="nav-link nav-menu-main menu-toggle hidden-xs"><i class="ft-menu font-large-1"></i></a></li>
                <li class="nav-item">
                    <a href=@Url.Action("Index","Home") class="navbar-brand">
                        <!--<img alt="stack admin logo" src="https://irp-cdn.multiscreensite.com/df4534bf/dms3rep/multi/tablet/cmsicon-476x407.png"
                        class="brand-logo" style="width:40px;">-->
                        <h2 class="brand-text">Andhra Views</h2>
                    </a>
                </li>
                <li class="nav-item d-md-none">
                    <a data-toggle="collapse" data-target="#navbar-mobile" class="nav-link open-navbar-container"><i class="fa fa-ellipsis-v"></i></a>
                </li>
            </ul>
        </div>
        <div class="navbar-container content">
            <div id="navbar-mobile" class="collapse navbar-collapse">
                <ul class="nav navbar-nav mr-auto float-left">
                    <li class="nav-item d-none d-md-block"><a href="#" class="nav-link nav-link-expand"><i class="ficon ft-maximize"></i></a></li>
                </ul>
                <ul class="nav navbar-nav float-right"> 
                    <li class="dropdown dropdown-user nav-item">
                        <a href="#" data-toggle="dropdown" class="dropdown-toggle nav-link dropdown-user-link">
                            <span class="avatar avatar-online">
                                <img src="~/web/app-assets/images/portrait/small/avatar-s-1.png" alt="avatar" /><i></i>
                            </span>
                            <span class="user-name">Admin</span>
                        </a>

                        <div class="dropdown-menu dropdown-menu-right">
                            @*<a class="dropdown-item" href="#"><i class="fa fa-pencil fa-fw"></i>Change Password</a>*@
                            @*<div class="dropdown-divider"></div>*@
                            <a class="dropdown-item" href="@Url.Action("Logout", "Login")"><i class="ft-power"></i> Logout</a>
                        </div>
                    </li>
                </ul>
            </div>
        </div>
    </div>
</nav>
<!-- ////////////////////////////////////////////////////////////////////////////-->
<!-- - var menuBorder = true-->
<div data-scroll-to-active="true" class="main-menu menu-fixed menu-light menu-accordion">
    <div class="main-menu-content">

        <ul id="main-menu-navigation" data-menu="menu-navigation" class="navigation navigation-main">

            @foreach (var item in Model)
            {
                if (item.isParent == false && item.parentId == 0)
                {
                    <li class=" nav-item">
                        <a href="@Url.Action(item.action, item.controller)"><i class="@item.imageClass"></i><span data-i18n="" class="menu-title">@item.nameOption</span></a>
                    </li>
                }
                else
                {
                    if (item.isParent == true)
                    {

                        <li class=" nav-item">
                            <a href="#"><i class="@item.imageClass"></i><span data-i18n="" class="menu-title">@item.nameOption</span></a>
                            <ul class="menu-content">
                                @foreach (var child in Model.Where(p => p.parentId == item.Id))
                                {
                                    if (child.controller == null)
                                    {
                                        <li><a href="#" class="menu-item">@child.nameOption</a></li>
                                    }
                                    else
                                    {
                                        <li><a href="@Url.Action(child.action, child.controller)" class="menu-item">@child.nameOption</a></li>
                                    }
                                }
                            </ul>
                        </li>
                       
                    }
                }
            }

            <li class=" nav-item">
                <a href="#"><i class="fa fa-podcast" ></i><span data-i18n="" class="menu-title">Redeem Request</span></a>
                <ul class="menu-content">

                    <li><a href="@Url.Action("Requests", "Redemption", new { Type = "Pending" })" class="menu-item">Pending</a></li>
                    <li><a href="@Url.Action("Requests", "Redemption", new { Type = "Approved" })" class="menu-item">Approved</a></li>
                    
                </ul>
            </li>

            @*<li class=" nav-item">
                <a href="@Url.Action("PointsDefinition", "Redemption", new { Type = "Pending" })"><i class="fa fa-diamond"></i><span data-i18n="" class="menu-title">Points Detail</span></a>
            </li>*@

            <li class=" nav-item">
                <a href="#"><i class="ft-align-left"></i><span data-i18n="" class="menu-title">Reports</span></a>
                <ul class="menu-content">
                    <li><a href="@Url.Action("Index", "Reports", new { ReportType = "ADD" })" class="menu-item">Advertisement</a></li>
                    <li><a href="@Url.Action("Index", "Reports", new { ReportType = "VIDEO" })" class="menu-item">Video</a></li>
                    <li><a href="@Url.Action("Index", "Reports", new { ReportType = "BANNER" })" class="menu-item">Banner</a></li>
                    <li><a href="@Url.Action("Index", "Reports", new { ReportType = "USER" })" class="menu-item">User</a></li>
                    <li><a href="@Url.Action("Index", "Reports", new { ReportType = "CUSTOMER" })" class="menu-item">Customer</a></li>
                    <li><a href="@Url.Action("Index", "Reports", new { ReportType = "CUSTOMERACTIVITY" })" class="menu-item">Customer Activity</a></li>
                    @*<li><a href="@Url.Action("Index", "Reports", new { ReportType = "STORE" })" class="menu-item">Store</a></li>*@
                </ul>
            </li>


        </ul>

    </div>
</div>